name: Ruff

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ruff-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ruff:
    name: Ruff checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/ruff-action@v3
        with:
          version: "0.5.7"
          args: "format --check"

      - uses: astral-sh/ruff-action@v3
        with:
          version: "0.5.7"
          args: "check"
