name: Ruff Lint and Format

on:
  push:
    paths:
      - "**.py"
  pull_request:
    paths:
      - "**.py"

jobs:
  ruff:
    name: Ruff Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install Ruff
        run: pip install ruff

      - name: Check formatting with Ruff
        run: ruff format --check .

      - name: Run Ruff linting with GitHub annotations
        run: ruff check --output-format=github .
