name: Publish

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: Build sdist/wheel
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: python -m pip install --upgrade pip build
      - run: python -m build
      - name: Check distributions
        run: |
          python -m pip install --upgrade twine
          python -m twine check dist/*

      - name: Smoke test wheel
        run: |
          python -m venv /tmp/venv
          . /tmp/venv/bin/activate
          python -m pip install dist/*.whl
          python -c "import dxf2geo; print('import OK')"

      - name: Upload artefacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/*

  publish-testpypi:
    name: Publish to TestPyPI
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - name: Publish (TestPyPI)
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/

  publish-pypi:
    name: Publish to PyPI
    needs: [build, publish-testpypi]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - name: Publish (PyPI)
        uses: pypa/gh-action-pypi-publish@release/v1

