name: Run Pytest

on:
  push:
    branches: [main]
    paths:
      - "**.py"
  pull_request:
    branches: [main]
    paths:
      - "**.py"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: env.yml
          activate-environment: test-env
          use-mamba: true

      - name: Install package
        shell: bash
        run: |
          source "${CONDA}/etc/profile.d/conda.sh"
          conda activate test-env
          pip install -e .

      - name: Run tests with pytest
        shell: bash
        run: |
          source "${CONDA}/etc/profile.d/conda.sh"
          conda activate test-env
          pytest
